import { BarChart3, Brain, TrendingUp, LineChart, Activity, Target } from "lucide-react";

const features = [
  {
    icon: BarChart3,
    title: "Comprehensive Factor Analysis",
    description: "Analyze stocks using 11 sophisticated factors including technical indicators, fundamental metrics, market dynamics, and sentiment analysis.",
    color: "blue",
    highlights: ["MA20/50/200", "RSI & Volume", "Market Cap & Liquidity"]
  },
  {
    icon: Brain,
    title: "AI-Powered Insights",
    description: "Get intelligent buy/sell recommendations with confidence scores generated by advanced AI models powered by LiteLLM integration.",
    color: "indigo",
    highlights: ["Price Predictions", "Sentiment Analysis", "Risk Assessment"]
  },
  {
    icon: TrendingUp,
    title: "Real-Time Analysis",
    description: "Monitor stock movements with real-time technical indicators, price alerts, and automated scoring for high-probability trading opportunities.",
    color: "purple",
    highlights: ["Live Price Data", "Technical Signals", "Daily Scoring"]
  },
  {
    icon: LineChart,
    title: "Advanced Charting",
    description: "Visualize stock performance with interactive charts, overlay multiple indicators, and compare historical patterns for better decision-making.",
    color: "cyan",
    highlights: ["Interactive Charts", "Pattern Recognition", "Historical Analysis"]
  },
  {
    icon: Activity,
    title: "Multi-Market Support",
    description: "Access analysis tools for both US and Vietnamese stock markets with market-specific factors and localized data sources.",
    color: "pink",
    highlights: ["US Markets", "Vietnamese VN30", "Global Coverage"]
  },
  {
    icon: Target,
    title: "Personalized Tracking",
    description: "Create custom watchlists, save favorite analyses, and receive personalized alerts based on your investment criteria and risk preferences.",
    color: "amber",
    highlights: ["Custom Watchlists", "Smart Alerts", "Portfolio Tracking"]
  }
];

const colorClasses = {
  blue: {
    bg: "bg-blue-100",
    icon: "text-blue-600",
    border: "border-blue-200"
  },
  indigo: {
    bg: "bg-indigo-100",
    icon: "text-indigo-600",
    border: "border-indigo-200"
  },
  purple: {
    bg: "bg-purple-100",
    icon: "text-purple-600",
    border: "border-purple-200"
  },
  cyan: {
    bg: "bg-cyan-100",
    icon: "text-cyan-600",
    border: "border-cyan-200"
  },
  pink: {
    bg: "bg-pink-100",
    icon: "text-pink-600",
    border: "border-pink-200"
  },
  amber: {
    bg: "bg-amber-100",
    icon: "text-amber-600",
    border: "border-amber-200"
  }
};

export function FeaturesSection() {
  return (
    <section className="bg-white py-20 sm:py-24">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section header */}
        <div className="mx-auto mb-16 max-w-3xl text-center">
          <h2 className="mb-4 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">
            Everything You Need for Smart Investing
          </h2>
          <p className="text-lg text-slate-600">
            Powerful features designed to help you make data-driven investment decisions with confidence.
          </p>
        </div>

        {/* Features grid */}
        <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
          {features.map((feature) => {
            const Icon = feature.icon;
            const colors = colorClasses[feature.color as keyof typeof colorClasses];

            return (
              <div
                key={feature.title}
                className="group relative rounded-xl border border-slate-200 bg-white p-6 shadow-sm transition-all hover:shadow-lg hover:border-slate-300"
              >
                {/* Icon */}
                <div className={`mb-4 inline-flex rounded-lg ${colors.bg} p-3`}>
                  <Icon className={`h-6 w-6 ${colors.icon}`} />
                </div>

                {/* Title */}
                <h3 className="mb-3 text-xl font-semibold text-slate-900">
                  {feature.title}
                </h3>

                {/* Description */}
                <p className="mb-4 text-slate-600">
                  {feature.description}
                </p>

                {/* Highlights */}
                <div className="flex flex-wrap gap-2">
                  {feature.highlights.map((highlight) => (
                    <span
                      key={highlight}
                      className={`rounded-full border ${colors.border} ${colors.bg} px-3 py-1 text-xs font-medium ${colors.icon}`}
                    >
                      {highlight}
                    </span>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
